version: '3'

services:
  app:
    build: ./docker/app
    command: node dummy-server.js
    working_dir: /usr/src/app
    volumes:
     - .:/usr/src/app
    ports:
     - "8080:80"
    networks:
     - blockchain
  ganache:
    build: ./docker/ganache
    working_dir: /usr/src/app
    volumes:
     - .:/usr/src/app
    ports:
     - "8545:8545"
    networks:
     - blockchain
  geth:
    build: ./docker/geth
    volumes:
     - geth:/node
    ports:
     - "8545:8545"
     - "8546:8546"
     - "30303:30303"
     - "30303:30303/udp"
    environment:
     GOROOTBASE: /usr/local
     GOROOT: /usr/local/go
     GOPATH: /go
    networks:
     - blockchain
  rinkeby:
    build: ./docker/rinkeby
    volumes:
     - rinkeby:/node
    ports:
     - "8545:8545"
     - "8546:8546"
     - "30303:30303"
     - "30303:30303/udp"
    environment:
     GOROOTBASE: /usr/local
     GOROOT: /usr/local/go
     GOPATH: /go
    networks:
     - blockchain
volumes:
  geth:
    driver: "local"
  rinkeby:
    driver: "local"
networks:
  blockchain:
    driver: "bridge"
