version: '3'

services:
  app:
    build: ./docker/app
    command: node dummy-server.js
    working_dir: /usr/src/app
    volumes:
     - .:/usr/src/app
    ports:
     - "8080:80"
    networks:
     - blockchain
  ganache:
    build: ./docker/ganache
    command: ganache-cli --account="0x351494a5ae8f9b70a2a2fd482146ab4578f61d4d796685c597ec6683635a940e, 100000000000000000000" --account="0x4cd491f96e6623edb52719a8d4d1110a87d8d83e3fa86f8e14007cb3831c0a2b, 100000000000000000000" --account="0x0ef40e0d6ada046010b6965d73603cabae1a119ca804f5d9e9a9ce866b0bea7d, 100000000000000000000"
    ports:
     - "8545:8545"
    networks:
     - blockchain
  geth:
    build: ./docker/geth
    volumes:
      - ./geth/geth:/geth
      - ./geth/keystore:/keystore
    ports:
        - "8545:8545"
        - "8546:8546"
        - "30303:30303"
        - "30303:30303/udp"
    environment:
      GOROOTBASE: /usr/local
      GOROOT: /usr/local/go
      GOPATH: /go
    networks:
      - blockchain
volumes:
  geth:
    driver: "local"
networks:
  blockchain:
    driver: "bridge"
